### ISSUE TITLE
How to resume training

### ISSUE THREAD

**Issue by PS-AI** [152334H/DL-Art-School#7]
Hi,
Thank you for your work.

I was able to follow the steps given in Readme.md file and start training the autoregressive.pth. But, my training crashed mid-way due to lack of server space. Therefore, I would like to resume training from the latest epoch.

My question is : - Should I just set the 'resume_state' value to point to the latest training state file 
OR
Should I also change the 'pretrain_model_gpt' to point to the latest epoch PTH file rather than the downloaded autoregressive.pth

**Comment by 152334H** [comment]
Hi, you should comment out `pretrain_model_gpt`, and edit the `resume_state` file to match the latest training state file. e.g.

```yml
path:
  #pretrain_model_gpt: '../experiments/autoregressive.pth'
  strict_load: true
  resume_state: ../experiments/MyExperimentName/training_state/600.state   # <-- Set this to resume from a previous training state.
```

I will add this as documentation to the README.
